version: 2
jobs:
  build:
    working_directory: /lem
    docker:
      - image: docker:17.10.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/lem.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/lem.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=lem -t lem .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/lem.tar lem
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/lem.tar